# Website 1: web1.local
server {
    listen 80;
    server_name web1.local;

    location / {
        root /usr/share/nginx/html/site1;
        index index.html;
    }

    # Proxy API sang Node-RED
    location /api/ {
        proxy_pass http://nodered:1880/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# Website 2: web2.local
server {
    listen 80;
    server_name web2.local;

    location / {
        root /usr/share/nginx/html/site2;
        index index.html;
    }
}
