server {
    listen 80;
    server_name web1.local;

    location / {
        root /usr/share/nginx/html/web1;
        index index.html;
    }

    # Đoạn này quyết định việc gọi API qua Nginx:
    location /api/ {
        proxy_pass http://nodered:1880/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
